### ISSUE TITLE
Error when trying to sync on Windows10, Kodi 15

### ISSUE THREAD

**Issue by mmesnjak** [MediaBrowser/Emby.Kodi#15]
Hi,

I get the following error after installing and configuring Emby for Kodi plugin and starting manual sync:

```
22:16:20 T:13028  NOTICE: -->Python Interpreter Initialized<--
22:16:20 T:13028  NOTICE: plugin.video.emby started
22:16:20 T:13028  NOTICE: Parameter string: ?mode=manualsync
22:16:20 T:13028  NOTICE: [Error 5] Access is denied: 'C:\\Users\\Mi\xc5\xa1el'
22:16:20 T:13028  NOTICE: Sync DB -> syncDatabase Exiting
22:16:20 T:13028   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u0161' in position 24: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Mi�el\AppData\Roaming\Kodi\addons\plugin.video.emby\default.py", line 125, in <module>
                                                Main()
                                              File "C:\Users\Mi�el\AppData\Roaming\Kodi\addons\plugin.video.emby\default.py", line 66, in __init__
                                                LibrarySync().FullLibrarySync(True)
                                              File "C:\Users\Mi�el\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\LibrarySync.py", line 147, in FullLibrarySync
                                                self.MoviesFullSync(connection,cursor,pDialog)
                                              File "C:\Users\Mi�el\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\LibrarySync.py", line 228, in MoviesFullSync
                                                views = ReadEmbyDB().getCollections("movies")
                                              File "C:\Users\Mi�el\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\ReadEmbyDB.py", line 285, in getCollections
                                                jsondata = self.doUtils.downloadUrl(url)
                                              File "C:\Users\Mi�el\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\DownloadUtils.py", line 224, in downloadUrl
                                                header = self.getHeader()
                                              File "C:\Users\Mi�el\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\DownloadUtils.py", line 168, in getHeader
                                                deviceId = clientInfo.getMachineId()
                                              File "C:\Users\Mi�el\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\ClientInformation.py", line 86, in getMachineId
                                                lock.release()
                                              File "C:\Users\Mi�el\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\Lock.py", line 36, in release
                                                xbmc.log("File_Lock_On " + self.filename + " released")
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u0161' in position 24: ordinal not in range(128)
                                            -->End of Python script error report<--
22:16:20 T:13028 WARNING: CPythonInvoker(35, C:\Users\Mišel\AppData\Roaming\Kodi\addons\plugin.video.emby\default.py): the python script "C:\Users\Mišel\AppData\Roaming\Kodi\addons\plugin.video.emby\default.py" has left several classes in memory that we couldn't clean up. The classes include: class PythonBindings::XBMCAddon_xbmc_Monitor_Director,class XBMCAddon::xbmcaddon::Addon,class XBMCAddon::xbmcgui::Window
22:16:20 T:5632   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.emby/?mode=manualsync
22:16:20 T:5632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.emby/?mode=manualsync) failed
22:16:20 T:12548  NOTICE: Thread LanguageInvoker start, auto delete: false
22:16:20 T:12548  NOTICE: -->Python Interpreter Initialized<--
22:16:21 T:12548  NOTICE: plugin.video.emby started
22:16:21 T:12548  NOTICE: Parameter string: ?content_type=executable
22:16:21 T:12548  NOTICE: plugin.video.emby stopped
22:16:21 T:11104  NOTICE: Thread BackgroundLoader start, auto delete: false
22:16:25 T:5632  NOTICE: Storing total System Uptime
22:16:25 T:5632  NOTICE: Saving settings
22:16:25 T:5632  NOTICE: stop all
22:16:25 T:5632  NOTICE: stop player
22:16:25 T:5632  NOTICE: ES: Stopping event server
22:16:25 T:5632  NOTICE: stopping upnp
22:16:25 T:5632  NOTICE: Webserver: Stopping...
22:16:25 T:5632  NOTICE: WebServer: Stopped the webserver
22:16:25 T:5632  NOTICE: Webserver: Stopped...
22:16:25 T:4380  NOTICE: ES: UDP Event server stopped
22:16:26 T:5632  NOTICE: stop sap announcement listener
22:16:26 T:5632  NOTICE: stop zeroconf browser
22:16:26 T:5632  NOTICE: clean cached files!
22:16:26 T:5632  NOTICE: unload skin
22:16:26 T:2080 WARNING: CPythonInvoker(1, C:\Users\Mišel\AppData\Roaming\Kodi\addons\service.skin.widgets\default.py): the python script "C:\Users\Mišel\AppData\Roaming\Kodi\addons\service.skin.widgets\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::Window,class PythonBindings::XBMCAddon_xbmc_Monitor_Director,class PythonBindings::XBMCAddon_xbmc_Player_Director
22:16:27 T:9776 WARNING: CPythonInvoker(4, C:\Users\Mišel\AppData\Roaming\Kodi\addons\service.library.data.provider\service.py): the python script "C:\Users\Mišel\AppData\Roaming\Kodi\addons\service.library.data.provider\service.py" has left several classes in memory that we couldn't clean up. The classes include: class PythonBindings::XBMCAddon_xbmc_Player_Director,class XBMCAddon::xbmcgui::Window,class PythonBindings::XBMCAddon_xbmc_Monitor_Director
22:16:27 T:5632  NOTICE: stopped
22:16:27 T:5632  NOTICE: destroy
22:16:27 T:5632  NOTICE: closing down remote control service
22:16:27 T:5632  NOTICE: unload sections
22:16:27 T:5632  NOTICE: special://profile/ is mapped to: special://masterprofile/
22:16:27 T:5632  NOTICE: destroy
22:16:27 T:5632 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
22:16:27 T:5632 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
22:16:27 T:5632  NOTICE: closing down remote control service
22:16:27 T:5632  NOTICE: unload sections
22:16:27 T:5632  NOTICE: application stopped...
22:16:27 T:5632   ERROR: dllFreeLibrary - Invalid hModule specified
```

**Comment by angelblue05** [comment]
Thank for reporting this issue. I will look into it.

**Comment by angelblue05** [comment]
The fix is now on Github. You can grab the zip and install/test and let me know if it fixes your issue. Thank you

**Comment by mmesnjak** [comment]
Hi angelblue05,

I'll do that tonight after work and report back. Thank you!

**Comment by angelblue05** [comment]
@mmesnjak 

Don't forget to let me know :) The fix is contained in the latest beta version 1.1.53

**Comment by mmesnjak** [comment]
Hi angelblue05,

Sorry for not getting back right away...
Now the plugin works just fine. Thank you!
