### ISSUE TITLE
Emby addon incompatible with / not available for Kodi 21 beta 1

### ISSUE THREAD

**Issue by Newcomer365** [MediaBrowser/Emby.Kodi#481]
Hi guys, it seems that the plugin does not work on the latest kodi v21, it gives an error when installing, and cannot configure the server after installation.  Kodi v21 has better support for Dolby, making it difficult to choose.  Reinstalled, same result.  Android.

**Comment by AdamN1** [comment]
Bellow is log from kodi
```
2023-11-10 10:15:11.330 T:1320    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'xml.etree.ElementTree.ParseError'>
                                                   Error Contents: not well-formed (invalid token): line 46, column 0
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.emby-next-gen/service.py", line 6, in <module>
                                                       hooks.monitor.StartUp()
                                                     File "/storage/.kodi/addons/plugin.video.emby-next-gen/hooks/monitor.py", line 781, in StartUp
                                                       Ret = setup()
                                                             ^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.emby-next-gen/hooks/monitor.py", line 745, in setup
                                                       xmls.sources()
                                                     File "/storage/.kodi/addons/plugin.video.emby-next-gen/helper/xmls.py", line 18, in sources
                                                       xmlData = xml.etree.ElementTree.fromstring(xmlData)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1338, in XML
                                                   xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 46, column 0
                                                   -->End of Python script error report<--
                                                   
2023-11-10 10:15:11.331 T:1320     info <general>: CPythonInvoker(1, /storage/.kodi/addons/plugin.video.emby-next-gen/service.py): waiting on thread 546081205952
```

I installed addon from stable and beta repository, behavior is the same.

**Comment by quickmic** [comment]
Kodi bug -> https://github.com/xbmc/xbmc/issues/24135
9.0.0 (currently under development) adds workaround for the issue.
